include: [.tmux.conf.md]
remote_theme: pages-themes/hacker@v0.2.0
enable_copy_code_button: true
mermaid:
  version="10.4.0"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-spaceship


