include: [.tmux.conf.md]
remote_theme: pages-themes/hacker@v0.2.0
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
enable_copy_code_button: true
mermaid:
  version="10.4.0"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one